### ISSUE TITLE
Provide a way to overwrite the user agent

### ISSUE THREAD

**Issue by mgol** [google/karma-webkit-launcher#2]
Playwright WebKit as provided by this package has different user agent on macOS:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)
```
than on Ubuntu 22.04.1 (e.g. used in GitHub Actions when `ubuntu-latest` is specified):
```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
```
Especially the latter version makes it very hard to distinguish from a real Safari version. They can also always change.

I'm trying to hook up WebKit testing in jQuery CI using this package in https://github.com/jquery/jquery/pull/5190. Some of our tests [verify whether support tests results match the expected values in each browser](https://github.com/jquery/jquery/blob/c66d4700dcf98efccb04061d575e242d28741223/test/unit/support.js#L61-L84). When a browser fixes one of the issues and we test both an old & a new version, we differentiate the assertion using version numbers.

You can see how this gets problematic with the Playwright WebKit user agents. If we were able to overwrite the UA, that would help as I could add the `playwright` token in there. It'd be ideal - but not fully necessary - if this override was a function that accepts the original UA so that I may tweak it without necessarily fully replacing it.

**Comment by mgol** [comment]
BTW, if there's any other way to detect the Playwright-provided WebKit in runtime, that would help as well, even without a UA override.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback, I will take a closer look into this in the next days.

The current version of Playwright uses a shell script to launch the headless browser like mentioned in #1.
For this reason it's isolated and there is no easy way to overwrite the UA.

But let me check, if I could integrate something over the karma tester itself.

**Comment by MarkusBordihn** [comment]
I just added a easy possible to check if Playwright is used during the tests.

See: https://github.com/google/karma-webkit-launcher#detected-if-safari-or-playwright-is-used

**Comment by mgol** [comment]
@MarkusBordihn Where are you getting this `test_browser` query parameter from? I don't see anything like that; `document.referrer` is something like `http://localhost:9876/?id=58476138` and `window.location.search` is an empty string.

**Comment by mgol** [comment]
Never mind, I though it's a generic remark and not something that this launcher adds.

**Comment by mgol** [comment]
@MarkusBordihn Thanks. While testing the change, I found two issues (one being a regression), PTAL: #4 & #5.
