### ISSUE TITLE
Headless mode not working in karma-webkit-launcher 1.2.0

### ISSUE THREAD

**Issue by mgol** [google/karma-webkit-launcher#3]
I updated `karma-webkit-launcher` from `1.1.0` to `1.2.0` to get a resolution for #1 in my jQuery PR that I mentioned in #2 but now `WebkitHeadless` is no longer headless - a regular window appears.

You can test that easily on macOS by checking out my jQuery PR: https://github.com/jquery/jquery/pull/5190 and invoking the following in the project directory:
```
npm install
npx grunt
BROWSERS=WebkitHeadless npx grunt karma:main
```

**Comment by MarkusBordihn** [comment]
Thanks for the report. I submitted a fix (v1.3.1), but will not be able to test this on a real macOS until tomorrow.
According the automated tests it should work, but let me know if you run into any additional issues.

**Comment by mgol** [comment]
Thanks! `1.3.1` works properly for me.

**Comment by jzombie** [comment]
Can also confirm this is working as expected in Ubuntu test runner as well as in macOS Monterey.
