### ISSUE TITLE
Process doesn't automatically close on exit on `main` on macOS

### ISSUE THREAD

**Issue by mgol** [google/karma-webkit-launcher#5]
#1 strikes again; while `karma-webkit-launcher` `2.0.0` correctly kills Playwright processes, the version from the `main` branch (commit 6d3006851505227fad6a7f153eed4fc739e7f9f1) no longer does that.

I found that when testing out changes from #2.

**Comment by mgol** [comment]
Not sure what changed but I tried this again on latest `main` (commit 98119f1c211ee7cd4a8fdc8c2334d6b5db2b63d0) and it seems to kill the processes properly now.

**Comment by jzombie** [comment]
I had experienced this very same thing after one of the upgrades, and noticed it seemed to be resolved after a while.

I think that I either rebooted or wiped the node modules beforehand.  Can't recall now.
